#!/bin/bash
if [ -z "$1" ]; then
	echo "Usage: $0 <rsync-dest>" >&2
	exit 1
fi
chmod a+rX -R out 2>/dev/null

echo "Generating branch list..." >&2
rm -f out/revcache
./branches.sh -v | while read commit branch junk; do
	echo ":$commit $branch"
	./revlist.sh $branch
done >out/revcache

echo "Describing..." >&2
mkdir -p out/describe
(
	cd build
	for d in ../out/pass/* ../out/fail/*; do
		b=$(basename $d)
		git describe --all --contains --always $b >../out/describe/$b
	done
)

echo "Rsyncing..." >&2
exec rsync -zvaP --no-owner --exclude '*~' \
	out viewer \
	"$1"
