#!/usr/bin/perl -w
use strict;
use LockFile::Simple;

if (@ARGV < 2) {
    print STDERR "Usage: $0 <lockfile> <command line...>\n";
    exit 127;
}	

my $lm = LockFile::Simple->make(-stale=>1) or die("makelock: $!\n");
my $filename = shift @ARGV;

my $lock = $lm->trylock($filename);
if (defined($lock)) {
    my $ret = system(@ARGV);
    $lock->release;
    exit $ret;
}

# didn't obtain lock, so didn't run; call that success, so we don't pop up
# annoying messages in cron.
print STDERR "Still locked.\n";
exit 0;
