#!/usr/bin/perl -w
use strict;
use LockFile::Simple;

if (@ARGV < 2) {
    print STDERR "Usage: $0 <lockfile> <command line...>\n";
    exit 127;
}	

my $lm = LockFile::Simple->make(-stale=>1, -hold=>0) 
    or die("makelock: $!\n");
my $filename = shift @ARGV;

my $lock = $lm->trylock($filename);
if (defined($lock)) {
    my $pid = fork();
    if ($pid) {
	# parent
	local $SIG{INT} = sub { kill 2, $pid; };
	local $SIG{TERM} = sub { kill 15, $pid; };
	my $ret = waitpid $pid, 0;
	$lock->release;
	exit $ret;
    } else {
	# child
	exec(@ARGV);
    }
    my $ret = system(@ARGV);
}

# didn't obtain lock, so didn't run; call that success, so we don't pop up
# annoying messages in cron.
print STDERR "Still locked.\n";
exit 0;
